import { notFound } from "next/navigation";
const branches={
  dwarka:{name:"Dwarka",address:"Unit 12, Market Arcade, Sector 12, New Delhi",hours:"09:00–22:00",special:"Wedding assortments",image:"/images/branch-dwarka.webp"},
  rohini:{name:"Rohini",address:"Shop 7, Community Plaza, Sector 9, New Delhi",hours:"09:00–22:00",special:"Festive gift boxes",image:"/images/branch-rohini.webp"},
  "noida-sector-18":{name:"Noida Sector 18",address:"Kiosk 4, Central Market Walk, Sector 18, Noida",hours:"Weekday 10:00–21:00 · weekend hours need verification",special:"Corporate gifting",image:"/images/branch-noida.webp"},
  "lajpat-nagar":{name:"Lajpat Nagar",address:"18A, Central Market Lane, New Delhi",hours:"09:30–22:30",special:"Fresh mithai counter",image:"/images/branch-lajpat.webp"},
} as const;
export function generateStaticParams(){return Object.keys(branches).map(branch=>({branch}))}
export default async function DemoBranch({params}:{params:Promise<{branch:string}>}){const {branch}=await params;const b=branches[branch as keyof typeof branches];if(!b)notFound();return <main className="demo-site"><section className="demo-site__hero" style={{backgroundImage:`url(${b.image})`}}><div><p className="eyebrow" style={{color:"inherit"}}>Madhur Sweets · {b.name}</p><h1>Made slowly.<br/>Shared warmly.</h1></div></section><section className="demo-site__body"><p className="eyebrow">A fictional Locally demo branch</p><h2 style={{margin:"1rem 0"}}>Something sweet for every gathering.</h2><p className="muted">This app-hosted page is a stable PageSpeed target. Madhur Sweets, this location, address, phone and offerings are intentionally non-operational demo content.</p><div className="grid grid--3" style={{marginTop:"4rem"}}><div><p className="eyebrow">Find us</p><p>{b.address}</p></div><div><p className="eyebrow">Open</p><p>{b.hours}</p></div><div><p className="eyebrow">Known for</p><p>{b.special}</p></div></div><div className="section card"><p className="review-copy">“Freshness, generosity, and a little yellow box worth carrying home.”</p></div></section></main>}
