(function (root) {
  root.LocallySeed = {
    agency: { name: 'Northstar Local', user: 'Aditi Deshmukh', role: 'SEO analyst' },
    periods: {
      '2026-07': {
        label: 'July 2026',
        rating: 4.2,
        locations: 3,
        openActions: 7,
        awaitingReply: 5,
        reportDue: '5 days',
        reportStatus: 'Draft in progress',
        reviewCount: 184,
        responseRate: 82,
        ratingDelta: 0.1,
        completedActions: 9,
      },
      '2026-06': {
        label: 'June 2026',
        rating: 4.1,
        locations: 3,
        openActions: 5,
        awaitingReply: 3,
        reportDue: 'Sent 3 Jul',
        reportStatus: 'Shared with client',
        reviewCount: 161,
        responseRate: 76,
        ratingDelta: -0.1,
        completedActions: 7,
      },
    },
    locations: [
      {
        id: 'dwarka', name: 'Dwarka', short: 'DW', address: 'Sector 12 Market, Dwarka, New Delhi 110075', phone: '+91 11 4182 7650', website: 'madhursweets.in/dwarka', rating: 4.5, awaiting: 1, visibility: 'Improving', websiteScore: 62, status: 'Good', statusTone: 'success', manager: 'Rakesh Sharma',
        profile: [
          { label: 'Business name', value: 'Madhur Sweets — Dwarka', status: 'Verified', tone: 'success', source: 'Google Business Profile', checked: '14 Jul 2026', verifier: 'Aditi' },
          { label: 'Address', value: 'Sector 12 Market, Dwarka', status: 'Verified', tone: 'success', source: 'GBP + storefront photo', checked: '14 Jul 2026', verifier: 'Aditi' },
          { label: 'Phone', value: '+91 11 4182 7650', status: 'Verified', tone: 'success', source: 'Client confirmation', checked: '10 Jul 2026', verifier: 'Aditi' },
          { label: 'Website', value: 'madhursweets.in/dwarka', status: 'Live', tone: 'success', source: 'Manual check', checked: '15 Jul 2026', verifier: 'Aditi' },
          { label: 'Opening hours', value: '09:00–22:00 daily', status: 'Verified', tone: 'success', source: 'Branch manager', checked: '14 Jul 2026', verifier: 'Aditi' },
          { label: 'Primary category', value: 'Sweet shop', status: 'Verified', tone: 'success', source: 'Google Business Profile', checked: '12 Jul 2026', verifier: 'Aditi' },
          { label: 'Additional categories', value: 'Dessert shop, Caterer', status: 'Review', tone: 'warning', source: 'Manual entry', checked: '8 Jul 2026', verifier: 'Aditi' },
          { label: 'Photo freshness', value: 'Last photo added 19 days ago', status: 'Fresh', tone: 'success', source: 'Google Business Profile', checked: '14 Jul 2026', verifier: 'Aditi' },
        ],
        completeness: 92,
        performance: {
          '2026-07': { search: 18420, maps: 11280, website: 2134, directions: 896, calls: 442 },
          '2026-06': { search: 16910, maps: 10240, website: 1965, directions: 832, calls: 419 },
        },
      },
      {
        id: 'rohini', name: 'Rohini', short: 'RH', address: 'Sector 9, Rohini, New Delhi 110085', phone: '+91 11 4756 2280', website: 'madhursweets.in/rohini', rating: 4.3, awaiting: 0, visibility: 'Stable', websiteScore: 74, status: 'Verify', statusTone: 'warning', manager: 'Neha Batra',
        profile: [
          { label: 'Business name', value: 'Madhur Sweets — Rohini', status: 'Verified', tone: 'success', source: 'Google Business Profile', checked: '13 Jul 2026', verifier: 'Aditi' },
          { label: 'Address', value: 'Sector 9, Rohini', status: 'Verified', tone: 'success', source: 'GBP + storefront photo', checked: '13 Jul 2026', verifier: 'Aditi' },
          { label: 'Phone', value: '+91 11 4756 2280', status: 'Verified', tone: 'success', source: 'Client confirmation', checked: '9 Jul 2026', verifier: 'Aditi' },
          { label: 'Website', value: 'madhursweets.in/rohini', status: 'Live', tone: 'success', source: 'Manual check', checked: '15 Jul 2026', verifier: 'Aditi' },
          { label: 'Opening hours', value: '09:00–21:30 · festive hours pending', status: 'Needs verification', tone: 'warning', source: 'Google Business Profile', checked: '14 Jul 2026', verifier: 'Aditi' },
          { label: 'Primary category', value: 'Sweet shop', status: 'Verified', tone: 'success', source: 'Google Business Profile', checked: '13 Jul 2026', verifier: 'Aditi' },
          { label: 'Additional categories', value: 'Dessert shop', status: 'Verified', tone: 'success', source: 'Google Business Profile', checked: '13 Jul 2026', verifier: 'Aditi' },
          { label: 'Photo freshness', value: 'Last photo added 37 days ago', status: 'Update soon', tone: 'warning', source: 'Google Business Profile', checked: '13 Jul 2026', verifier: 'Aditi' },
        ],
        completeness: 84,
        performance: {
          '2026-07': { search: 15170, maps: 8940, website: 1760, directions: 742, calls: 385 },
          '2026-06': { search: 15080, maps: 8870, website: 1732, directions: 731, calls: 379 },
        },
      },
      {
        id: 'noida-sector-18', name: 'Noida Sector 18', short: 'N18', address: 'Atta Market, Sector 18, Noida 201301', phone: '+91 120 498 3100', website: 'madhursweets.in/noida-sector-18', rating: 3.8, awaiting: 4, visibility: 'Declining', websiteScore: 68, status: 'Critical', statusTone: 'danger', manager: 'Vikram Jain',
        profile: [
          { label: 'Business name', value: 'Madhur Sweets — Noida Sector 18', status: 'Verified', tone: 'success', source: 'Google Business Profile', checked: '14 Jul 2026', verifier: 'Aditi' },
          { label: 'Address', value: 'Atta Market, Sector 18, Noida', status: 'Verified', tone: 'success', source: 'GBP + storefront photo', checked: '14 Jul 2026', verifier: 'Aditi' },
          { label: 'Phone', value: '+91 120 498 3100', status: 'Verified', tone: 'success', source: 'Branch manager', checked: '14 Jul 2026', verifier: 'Aditi' },
          { label: 'Website', value: 'madhursweets.in/noida-sector-18', status: 'Live', tone: 'success', source: 'Manual check', checked: '15 Jul 2026', verifier: 'Aditi' },
          { label: 'Opening hours', value: '09:30–22:00', status: 'Needs verification', tone: 'warning', source: 'Google Business Profile', checked: '14 Jul 2026', verifier: 'Aditi' },
          { label: 'Primary category', value: 'Sweet shop', status: 'Verified', tone: 'success', source: 'Google Business Profile', checked: '12 Jul 2026', verifier: 'Aditi' },
          { label: 'Additional categories', value: 'Dessert shop, Indian takeaway', status: 'Review', tone: 'warning', source: 'Manual entry', checked: '7 Jul 2026', verifier: 'Aditi' },
          { label: 'Photo freshness', value: 'Last photo added 64 days ago', status: 'Stale', tone: 'danger', source: 'Google Business Profile', checked: '14 Jul 2026', verifier: 'Aditi' },
        ],
        completeness: 76,
        performance: {
          '2026-07': { search: 10840, maps: 6210, website: 1288, directions: 494, calls: 271 },
          '2026-06': { search: 11950, maps: 6990, website: 1398, directions: 548, calls: 302 },
        },
      },
    ],
    attention: [
      { id: 'critical-review', title: 'Critical review needs escalation', detail: 'Noida Sector 18 · Product quality', locationId: 'noida-sector-18', route: 'reviews', tone: 'danger', age: '18 min ago' },
      { id: 'keyword-decline', title: 'Two keywords declined this week', detail: '“mithai near me” dropped 2 positions', locationId: 'dwarka', route: 'visibility', tone: 'warning', age: 'Checked today' },
      { id: 'mobile-performance', title: 'Landing page is slow on mobile', detail: 'Dwarka · Performance score 62', locationId: 'dwarka', route: 'website-audit', tone: 'warning', age: 'Updated yesterday' },
      { id: 'closing-time', title: 'Closing time needs verification', detail: 'Rohini · Festive hours may differ', locationId: 'rohini', route: 'locations', tone: 'warning', age: 'Stale for 6 days' },
    ],
    weeklyChecklist: [
      { id: 'reviews', label: 'Reviews checked', done: true, owner: 'Aditi', evidence: '15 Jul · 09:42' },
      { id: 'rankings', label: 'Rankings recorded', done: true, owner: 'Aditi', evidence: '15 Jul · 10:18' },
      { id: 'competitors', label: 'Competitors reviewed', done: false, owner: 'Aditi', evidence: 'Due today' },
      { id: 'website', label: 'Website issues assigned', done: true, owner: 'Kabir', evidence: '14 Jul · 16:05' },
      { id: 'client-update', label: 'Client update prepared', done: false, owner: 'Aditi', evidence: 'Due Fri' },
    ],
    reviews: [
      { id: 'r1', reviewer: 'Prateek S.', stars: 1, locationId: 'noida-sector-18', date: '15 Jul 2026', text: 'The sweets seemed stale and the staff did not help when we complained. This was for a family function and was very disappointing.', category: 'Product quality', severity: 'Critical', status: 'Needs reply', escalation: 'Escalation required', source: 'Google Business Profile', checked: '15 Jul 2026 · 09:20', internalNote: 'Spoke with Vikram. Branch is checking the 14 July evening batch and counter CCTV. Do not promise compensation until manager confirms.', draft: 'Hello Prateek, thank you for bringing this to our attention. We are checking the batch and speaking with our Sector 18 team. We take freshness seriously and would like to understand your order details so we can address this properly.', approval: { facts: true, policy: false, manager: false } },
      { id: 'r2', reviewer: 'Aman Verma', stars: 3, locationId: 'dwarka', date: '14 Jul 2026', text: 'Good kaju katli but billing took too long in the evening.', category: 'Service', severity: 'Medium', status: 'Draft', source: 'Google Business Profile', checked: '14 Jul 2026 · 18:10', draft: 'Thank you for the feedback, Aman. We are glad you enjoyed the kaju katli and have shared the billing delay with our Dwarka team.', approval: { facts: true, policy: true, manager: false } },
      { id: 'r3', reviewer: 'Ritu Malhotra', stars: 2, locationId: 'noida-sector-18', date: '14 Jul 2026', text: 'The wedding box looked different from the sample shown.', category: 'Order accuracy', severity: 'High', status: 'Needs reply', source: 'Google Business Profile', checked: '14 Jul 2026 · 15:32', draft: '', approval: { facts: false, policy: false, manager: false } },
      { id: 'r4', reviewer: 'Nikhil A.', stars: 4, locationId: 'noida-sector-18', date: '13 Jul 2026', text: 'Fresh sweets and easy to find. Parking is difficult on weekends.', category: 'Store experience', severity: 'Low', status: 'Needs reply', source: 'Google Business Profile', checked: '13 Jul 2026 · 19:05', draft: '', approval: { facts: false, policy: false, manager: false } },
      { id: 'r5', reviewer: 'Megha Kapoor', stars: 5, locationId: 'rohini', date: '12 Jul 2026', text: 'Beautiful wedding hampers and very helpful staff.', category: 'Product praise', severity: 'Positive', status: 'Replied', source: 'Google Business Profile', checked: '12 Jul 2026 · 12:20', draft: 'Thank you, Megha. We are delighted the wedding hampers worked well for your celebration.', approval: { facts: true, policy: true, manager: true } },
      { id: 'r6', reviewer: 'Sanjay Mishra', stars: 2, locationId: 'noida-sector-18', date: '11 Jul 2026', text: 'Delivery was late and nobody picked up the phone.', category: 'Delivery', severity: 'High', status: 'Needs reply', source: 'Google Business Profile', checked: '11 Jul 2026 · 21:10', draft: '', approval: { facts: false, policy: false, manager: false } },
      { id: 'r7', reviewer: 'Kavya S.', stars: 5, locationId: 'dwarka', date: '8 Jul 2026', text: 'The motichoor laddoos were excellent and packed carefully.', category: 'Product praise', severity: 'Positive', status: 'Replied', source: 'Google Business Profile', checked: '8 Jul 2026 · 17:44', draft: 'Thank you, Kavya. We are so glad you enjoyed the laddoos.', approval: { facts: true, policy: true, manager: true } },
    ],
    visibility: [
      { id: 'v1', period: '2026-07', keyword: 'sweet shop in Dwarka', type: 'Google Maps', area: 'Dwarka', device: 'Mobile', previous: 7, current: 5, locationId: 'dwarka', checkedBy: 'Aditi', date: '15 Jul 2026', evidence: 'dwarka-map-1507.png' },
      { id: 'v2', period: '2026-07', keyword: 'mithai near me', type: 'Google Search', area: 'Sector 12', device: 'Mobile', previous: 4, current: 6, locationId: 'dwarka', checkedBy: 'Aditi', date: '15 Jul 2026', evidence: 'sector12-search.png' },
      { id: 'v3', period: '2026-07', keyword: 'wedding sweets Dwarka', type: 'Google Search', area: 'West Delhi', device: 'Desktop', previous: 12, current: 8, locationId: 'dwarka', checkedBy: 'Aditi', date: '15 Jul 2026', evidence: 'west-delhi-wedding.png' },
      { id: 'v4', period: '2026-07', keyword: 'sweet shop Rohini', type: 'Google Maps', area: 'Rohini Sec 9', device: 'Mobile', previous: 5, current: 5, locationId: 'rohini', checkedBy: 'Kabir', date: '14 Jul 2026', evidence: 'rohini-maps.png' },
      { id: 'v5', period: '2026-07', keyword: 'best mithai Noida', type: 'Google Maps', area: 'Sector 18', device: 'Mobile', previous: 6, current: 9, locationId: 'noida-sector-18', checkedBy: 'Aditi', date: '15 Jul 2026', evidence: 'noida-mithai.png' },
      { id: 'v6', period: '2026-07', keyword: 'wedding sweets Noida', type: 'Google Search', area: 'Central Noida', device: 'Desktop', previous: 10, current: 13, locationId: 'noida-sector-18', checkedBy: 'Aditi', date: '15 Jul 2026', evidence: 'noida-wedding.png' },
      { id: 'v7', period: '2026-06', keyword: 'sweet shop in Dwarka', type: 'Google Maps', area: 'Dwarka', device: 'Mobile', previous: 8, current: 7, locationId: 'dwarka', checkedBy: 'Aditi', date: '27 Jun 2026', evidence: 'dwarka-map-2706.png' },
      { id: 'v8', period: '2026-06', keyword: 'sweet shop Rohini', type: 'Google Maps', area: 'Rohini Sec 9', device: 'Mobile', previous: 6, current: 5, locationId: 'rohini', checkedBy: 'Kabir', date: '27 Jun 2026', evidence: 'rohini-maps-2706.png' },
      { id: 'v9', period: '2026-06', keyword: 'best mithai Noida', type: 'Google Maps', area: 'Sector 18', device: 'Mobile', previous: 5, current: 6, locationId: 'noida-sector-18', checkedBy: 'Aditi', date: '27 Jun 2026', evidence: 'noida-mithai-2706.png' },
    ],
    competitors: [
      { id: 'c1', locationId: 'dwarka', name: 'Bikaner House', rating: 4.4, reviews: 1820, distance: '1.2 km', category: 'Indian sweets', checked: '13 Jul 2026', strengths: ['Recent product photos', 'Higher review volume', 'Complete festive hours'], weaknesses: ['Slow owner responses', 'Generic service pages'], action: 'Update festive hours and publish recent product photography.' },
      { id: 'c2', locationId: 'dwarka', name: 'Kaleva', rating: 4.2, reviews: 1340, distance: '2.4 km', category: 'Sweet shop', checked: '13 Jul 2026', strengths: ['Strong wedding catalogue', 'Active Google Posts'], weaknesses: ['Inconsistent photo quality'], action: 'Build a dedicated wedding-order gallery for Dwarka.' },
      { id: 'c3', locationId: 'dwarka', name: 'Aggarwal Sweets', rating: 4.1, reviews: 920, distance: '800 m', category: 'Sweet shop', checked: '13 Jul 2026', strengths: ['Close proximity', 'High branded search visibility'], weaknesses: ['Few recent reviews', 'Missing product details'], action: 'Ask recent catering clients for branch-specific reviews.' },
      { id: 'c4', locationId: 'rohini', name: 'BTW Rohini', rating: 4.3, reviews: 2260, distance: '1.0 km', category: 'Indian restaurant', checked: '12 Jul 2026', strengths: ['Large review base', 'Consistent posts'], weaknesses: ['Low response rate'], action: 'Publish two Rohini product updates before Raksha Bandhan.' },
      { id: 'c5', locationId: 'rohini', name: 'Hira Sweets', rating: 4.2, reviews: 1430, distance: '1.8 km', category: 'Sweet shop', checked: '12 Jul 2026', strengths: ['Clear directions', 'Fresh storefront images'], weaknesses: ['Unclear festive schedule'], action: 'Refresh storefront and directions photography.' },
      { id: 'c6', locationId: 'rohini', name: 'Gopal Sweets', rating: 4.0, reviews: 710, distance: '650 m', category: 'Dessert shop', checked: '12 Jul 2026', strengths: ['Strong local relevance'], weaknesses: ['Thin website content'], action: 'Keep monitoring; no immediate response needed.' },
      { id: 'c7', locationId: 'noida-sector-18', name: 'Haldiram’s', rating: 4.5, reviews: 4420, distance: '900 m', category: 'Indian restaurant', checked: '14 Jul 2026', strengths: ['Very high review volume', 'Strong category coverage'], weaknesses: ['Mixed peak-hour service reviews'], action: 'Emphasize specialist wedding and gifting service.' },
      { id: 'c8', locationId: 'noida-sector-18', name: 'Bikanervala', rating: 4.3, reviews: 3160, distance: '1.5 km', category: 'Sweet shop', checked: '14 Jul 2026', strengths: ['Frequent photos', 'Accurate hours'], weaknesses: ['Low owner reply quality'], action: 'Resolve quality complaints before increasing promotion.' },
      { id: 'c9', locationId: 'noida-sector-18', name: 'Evergreen Sweets', rating: 4.1, reviews: 1120, distance: '1.1 km', category: 'Sweet shop', checked: '14 Jul 2026', strengths: ['Strong “near me” placement'], weaknesses: ['Outdated website'], action: 'Add location proof and category copy to the landing page.' },
    ],
    audit: {
      automated: [
        { id: 'performance', label: 'Performance', score: 62, status: 'Warning', tone: 'warning', locationId: 'dwarka', source: 'PageSpeed-style check', checked: '14 Jul 2026' },
        { id: 'accessibility', label: 'Accessibility', score: 88, status: 'Pass', tone: 'success', locationId: 'dwarka', source: 'PageSpeed-style check', checked: '14 Jul 2026' },
        { id: 'seo', label: 'SEO', score: 91, status: 'Pass', tone: 'success', locationId: 'dwarka', source: 'PageSpeed-style check', checked: '14 Jul 2026' },
        { id: 'best-practices', label: 'Best practices', score: 79, status: 'Warning', tone: 'warning', locationId: 'dwarka', source: 'PageSpeed-style check', checked: '14 Jul 2026' },
        { id: 'mobile-usability', label: 'Mobile usability', score: 68, status: 'Warning', tone: 'warning', locationId: 'noida-sector-18', source: 'Manual device test', checked: '14 Jul 2026' },
        { id: 'image-optimization', label: 'Image optimization', score: 54, status: 'Fail', tone: 'danger', locationId: 'dwarka', source: 'PageSpeed-style check', checked: '14 Jul 2026' },
      ],
      manual: [
        { id: 'business-name', label: 'Correct business name', status: 'Pass', tone: 'success', locationId: 'dwarka', note: 'Matches storefront and GBP.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'address', label: 'Correct address', status: 'Pass', tone: 'success', locationId: 'dwarka', note: 'Pin and footer address match.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'phone', label: 'Correct phone', status: 'Pass', tone: 'success', locationId: 'dwarka', note: 'Tap-to-call tested.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'branch-content', label: 'Branch-specific content', status: 'Warning', tone: 'warning', locationId: 'dwarka', note: 'Only 74 words are unique to Dwarka.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'map-embed', label: 'Google Map embed', status: 'Fail', tone: 'danger', locationId: 'dwarka', note: 'No embedded branch map found.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'hours', label: 'Opening hours', status: 'Pass', tone: 'success', locationId: 'dwarka', note: 'Matches verified GBP hours.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'clickable-phone', label: 'Clickable phone number', status: 'Pass', tone: 'success', locationId: 'dwarka', note: 'Working on Android and iOS.', verifier: 'Kabir', checked: '14 Jul 2026' },
        { id: 'directions', label: 'Directions button', status: 'Warning', tone: 'warning', locationId: 'dwarka', note: 'Button is below the first screen on mobile.', verifier: 'Kabir', checked: '14 Jul 2026' },
        { id: 'testimonials', label: 'Branch testimonials', status: 'Warning', tone: 'warning', locationId: 'dwarka', note: 'Testimonials do not name the branch.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'local-keywords', label: 'Local keywords', status: 'Pass', tone: 'success', locationId: 'dwarka', note: 'Dwarka and West Delhi used naturally.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'contact-page', label: 'Contact page', status: 'Pass', tone: 'success', locationId: 'dwarka', note: 'Branch details are complete.', verifier: 'Aditi', checked: '14 Jul 2026' },
        { id: 'trust-signals', label: 'Trust signals', status: 'Warning', tone: 'warning', locationId: 'dwarka', note: 'Add catering credentials and order policy.', verifier: 'Aditi', checked: '14 Jul 2026' },
      ],
    },
    actions: [
      { id: 'a1', title: 'Confirm festive opening hours', client: 'Madhur Sweets', locationId: 'rohini', source: 'GBP health check', priority: 'High', owner: 'Aditi', due: '16 Jul', status: 'Open' },
      { id: 'a2', title: 'Escalate stale-product complaint', client: 'Madhur Sweets', locationId: 'noida-sector-18', source: 'Review', priority: 'Urgent', owner: 'Aditi', due: 'Today', status: 'In progress' },
      { id: 'a3', title: 'Compress Dwarka landing-page images', client: 'Madhur Sweets', locationId: 'dwarka', source: 'Website audit', priority: 'High', owner: 'Kabir', due: '18 Jul', status: 'Open' },
      { id: 'a4', title: 'Request new Sector 18 product photos', client: 'Madhur Sweets', locationId: 'noida-sector-18', source: 'GBP health check', priority: 'Medium', owner: 'Aditi', due: '19 Jul', status: 'Waiting for client' },
      { id: 'a5', title: 'Add wedding-order content to Dwarka page', client: 'Madhur Sweets', locationId: 'dwarka', source: 'Competitor observation', priority: 'Medium', owner: 'Kabir', due: '22 Jul', status: 'Open' },
      { id: 'a6', title: 'Investigate “mithai near me” rank decline', client: 'Madhur Sweets', locationId: 'dwarka', source: 'Rank tracking', priority: 'Medium', owner: 'Aditi', due: '17 Jul', status: 'In progress' },
      { id: 'a7', title: 'Confirm Sector 18 replacement policy', client: 'Madhur Sweets', locationId: 'noida-sector-18', source: 'Client feedback', priority: 'High', owner: 'Aditi', due: 'Today', status: 'Waiting for client' },
      { id: 'a8', title: 'Publish Rohini storefront photos', client: 'Madhur Sweets', locationId: 'rohini', source: 'Competitor observation', priority: 'Low', owner: 'Kabir', due: '10 Jul', status: 'Completed', completedPeriod: '2026-07' },
      { id: 'a9', title: 'Correct Dwarka map pin', client: 'Madhur Sweets', locationId: 'dwarka', source: 'Client feedback', priority: 'High', owner: 'Aditi', due: '28 Jun', status: 'Completed', completedPeriod: '2026-06' },
    ],
    report: {
      '2026-07': {
        changed: 'Visibility improved in Dwarka, while Sector 18 lost ground across two high-intent searches. Review response improved, but a serious product-quality complaint remains unresolved.',
        reasons: 'Dwarka benefited from updated category information and more recent photos. Sector 18 has older imagery, lower review sentiment, and a landing page with limited local proof.',
        completed: 'Verified core profile information for all branches, corrected the Dwarka map pin, replied to 11 reviews, and assigned mobile performance fixes.',
        concerns: 'Sector 18 product-quality complaints require branch confirmation. Rohini festive closing time is still pending client verification.',
        priorities: ['Resolve recurring product-quality complaints at Sector 18', 'Improve Dwarka landing-page performance', 'Update festive information across all locations'],
        limitations: 'Rankings are manually checked from defined search areas and may vary by device, location, and personalisation. GBP performance data was last imported 2 hours ago.',
      },
      '2026-06': {
        changed: 'Overall visibility was stable. Dwarka recovered one Maps position and Rohini review volume increased.',
        reasons: 'Profile cleanup improved consistency, while content updates had not yet been published.',
        completed: 'Corrected the Dwarka map pin, verified phone numbers, and closed seven operational actions.',
        concerns: 'Sector 18 rating continued to trail the other branches.',
        priorities: ['Improve Sector 18 review response', 'Add branch-specific website content', 'Refresh location photography'],
        limitations: 'June rankings were manually checked on 27 June from one device per search area.',
      },
    },
    onboarding: {
      step: 1,
      completed: [],
      fields: {
        businessName: '', industry: 'Food & beverage', contact: '', website: '', locations: 'Dwarka\nRohini\nNoida Sector 18', priorityLocations: '', concerns: '', goals: ['maps', 'visits'], connection: 'manual',
      },
    },
    ui: { reviewFilter: 'All', selectedReview: null, locationTab: 'profile', actionStatus: 'All', auditView: 'manual', reportFeedback: null },
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
