alter function private.set_updated_at() set search_path = '';

-- Mutation policies are command-specific so they do not duplicate SELECT policies.
drop policy assignments_owner_all on public.client_assignments;
drop policy locations_agency_all on public.locations;
drop policy policies_agency_all on public.client_policies;
drop policy health_agency_all on public.gbp_health_checks;
drop policy performance_agency_all on public.location_performance_snapshots;
drop policy reviews_agency_all on public.reviews;
drop policy replies_agency_all on public.review_replies;
drop policy notes_agency_all on public.review_internal_notes;
drop policy audits_agency_all on public.website_audits;
drop policy audit_items_agency_all on public.website_audit_items;
drop policy competitors_agency_all on public.competitors;
drop policy actions_agency_all on public.actions;
drop policy reports_agency_all on public.monthly_updates;
drop policy deliveries_agency_all on public.email_deliveries;
drop policy usage_self_all on public.integration_usage;

create policy assignments_owner_insert on public.client_assignments for insert to authenticated with check (private.current_role()='agency_owner' and private.can_access_client(client_id));
create policy assignments_owner_delete on public.client_assignments for delete to authenticated using (private.current_role()='agency_owner' and private.can_access_client(client_id));
create policy locations_agency_insert on public.locations for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy locations_agency_update on public.locations for update to authenticated using (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id)) with check (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy locations_agency_delete on public.locations for delete to authenticated using (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy policies_agency_insert on public.client_policies for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy policies_agency_update on public.client_policies for update to authenticated using (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id)) with check (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy health_agency_insert on public.gbp_health_checks for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id)));
create policy health_agency_update on public.gbp_health_checks for update to authenticated using (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id))) with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id)));
create policy performance_agency_insert on public.location_performance_snapshots for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id)));
create policy reviews_agency_insert on public.reviews for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id)));
create policy reviews_agency_update on public.reviews for update to authenticated using (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id))) with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id)));
create policy replies_agency_insert on public.review_replies for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.reviews r join public.locations l on l.id=r.location_id where r.id=review_id and private.can_access_client(l.client_id)));
create policy replies_agency_update on public.review_replies for update to authenticated using (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.reviews r join public.locations l on l.id=r.location_id where r.id=review_id and private.can_access_client(l.client_id))) with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.reviews r join public.locations l on l.id=r.location_id where r.id=review_id and private.can_access_client(l.client_id)));
create policy notes_agency_insert on public.review_internal_notes for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.reviews r join public.locations l on l.id=r.location_id where r.id=review_id and private.can_access_client(l.client_id)));
create policy audits_agency_insert on public.website_audits for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id)));
create policy audit_items_agency_insert on public.website_audit_items for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.website_audits a join public.locations l on l.id=a.location_id where a.id=audit_id and private.can_access_client(l.client_id)));
create policy competitors_agency_insert on public.competitors for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id)));
create policy competitors_agency_update on public.competitors for update to authenticated using (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id))) with check (private.current_role() in ('agency_owner','seo_employee') and exists(select 1 from public.locations l where l.id=location_id and private.can_access_client(l.client_id)));
create policy actions_agency_insert on public.actions for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy actions_agency_update on public.actions for update to authenticated using (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id)) with check (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy reports_agency_insert on public.monthly_updates for insert to authenticated with check (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy reports_agency_update on public.monthly_updates for update to authenticated using (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id)) with check (private.current_role() in ('agency_owner','seo_employee') and private.can_access_client(client_id));
create policy deliveries_owner_insert on public.email_deliveries for insert to authenticated with check (private.current_role()='agency_owner' and private.can_access_client(client_id));
create policy usage_self_insert on public.integration_usage for insert to authenticated with check (user_id=(select auth.uid()));
create policy usage_self_update on public.integration_usage for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));

drop policy feedback_client_insert on public.report_feedback;
drop policy feedback_client_update on public.report_feedback;
create policy feedback_client_insert on public.report_feedback for insert to authenticated with check (client_user_id=(select auth.uid()) and exists(select 1 from public.monthly_updates m where m.id=monthly_update_id and m.client_id=private.current_client_id() and m.status in ('approved','sent')));
create policy feedback_client_update on public.report_feedback for update to authenticated using (client_user_id=(select auth.uid())) with check (client_user_id=(select auth.uid()));

create index if not exists actions_assigned_to_idx on public.actions(assigned_to);
create index if not exists actions_created_by_idx on public.actions(created_by);
create index if not exists actions_location_id_idx on public.actions(location_id);
create index if not exists competitors_created_by_idx on public.competitors(created_by);
create index if not exists deliveries_attempted_by_idx on public.email_deliveries(attempted_by);
create index if not exists deliveries_client_id_idx on public.email_deliveries(client_id);
create index if not exists deliveries_report_id_idx on public.email_deliveries(monthly_update_id);
create index if not exists health_verified_by_idx on public.gbp_health_checks(verified_by);
create index if not exists reports_approved_by_idx on public.monthly_updates(approved_by);
create index if not exists reports_created_by_idx on public.monthly_updates(created_by);
create index if not exists onboarding_reviewed_by_idx on public.onboarding_submissions(reviewed_by);
create index if not exists onboarding_submitted_by_idx on public.onboarding_submissions(submitted_by);
create index if not exists profiles_client_id_idx on public.profiles(client_id);
create index if not exists feedback_client_user_idx on public.report_feedback(client_user_id);
create index if not exists notes_created_by_idx on public.review_internal_notes(created_by);
create index if not exists notes_review_id_idx on public.review_internal_notes(review_id);
create index if not exists replies_approved_by_idx on public.review_replies(approved_by);
create index if not exists replies_created_by_idx on public.review_replies(created_by);
create index if not exists replies_mock_published_by_idx on public.review_replies(mock_published_by);
create index if not exists replies_acknowledged_by_idx on public.review_replies(warnings_acknowledged_by);
create index if not exists audit_items_audit_id_idx on public.website_audit_items(audit_id);
create index if not exists audits_location_id_idx on public.website_audits(location_id);
create index if not exists audits_run_by_idx on public.website_audits(run_by);
