import Link from "next/link";
import { activateClientAction } from "@/app/actions/onboarding";
import { addLocationAction, assignSpecialistAction, sendOnboardingInviteAction, updateClientStatusAction } from "@/app/actions/clients";
import { PendingButton } from "@/components/pending-button";
import { Badge, Card, Input, Label } from "@/components/ui";
import { Section } from "@/components/section";
import { requireActor } from "@/lib/auth";
import { getClient, getClients, getProfiles } from "@/lib/data";
import { formatDate, sourceLabel, titleCase } from "@/lib/format";

export default async function ClientDetail({params}:{params:Promise<{clientId:string}>}){
  const {clientId}=await params;
  const [d,actor,clients,profiles]=await Promise.all([getClient(clientId),requireActor(["agency_owner","seo_employee"]),getClients(),getProfiles()]);
  const directory=clients.find(c=>c.id===clientId);const specialist=profiles.find(p=>p.role==="seo_employee");const assigned=Boolean(specialist&&directory?.client_assignments.some(a=>a.user_id===specialist.id));
  return <>
    <div className="page-head"><div><p className="eyebrow">{d.client.industry}</p><h1>{d.client.business_name}</h1><p>{d.client.goals instanceof Array?d.client.goals.join(" · "):"A clear view of local-search work."}</p></div><Badge tone={d.client.status==="active"?"good":"warn"}>{titleCase(d.client.status)}</Badge></div>
    <div className="tabs"><Link href={`/agency/clients/${clientId}`}>Overview</Link><Link href={`/agency/reviews?client=${clientId}`}>Reviews</Link><Link href="/agency/audits">Audits</Link><Link href="/agency/competitors">Competitors</Link><Link href="/agency/actions">Actions</Link><Link href="/agency/reports">Reports</Link></div>
    <Section number="01" title="The branch picture"><div className="grid grid--2">{d.locations.map(l=>{const p=d.performance.find(x=>x.location_id===l.id);return <Card key={l.id}><div className="card__meta"><Badge tone="accent">Demo data</Badge><span className="muted">{l.city}</span></div><h3>{l.name}</h3><p className="muted">{l.address}</p><div className="grid grid--2" style={{marginTop:"1.7rem"}}><div><p className="eyebrow">Rating</p><p className="card__value">{p?.average_rating??"—"}</p></div><div><p className="eyebrow">Reviews</p><p className="card__value">{p?.review_count??"—"}</p></div></div></Card>})}</div></Section>
    <Section number="02" title="Actions in motion"><Card>{d.actions.map((a,i)=><div className="list-row" key={a.id}><span className="list-row__index">{String(i+1).padStart(2,"0")}</span><span><strong>{a.title}</strong><br/><small className="muted">{sourceLabel[a.source_type]??titleCase(a.source_type)} · {a.due_date?formatDate(a.due_date):"No due date"}</small></span><Badge tone={a.status==="done"?"good":a.priority==="high"?"bad":"neutral"}>{titleCase(a.status)}</Badge></div>)}</Card></Section>
    <Section number="03" title="Onboarding and access" intro="Agency-only controls are kept outside the client-visible profile."><div className="grid grid--2"><Card className="stack"><p><strong>Survey:</strong> {titleCase(d.onboarding?.status??"not_started")}</p><p><strong>Current step:</strong> {d.onboarding?.current_step??"—"} / 4</p><form action={sendOnboardingInviteAction}><input type="hidden" name="clientId" value={clientId}/><PendingButton pendingLabel="Sending onboarding email…">Send onboarding email</PendingButton></form>{actor.role==="agency_owner"&&<form action={activateClientAction}><input type="hidden" name="clientId" value={clientId}/><PendingButton variant="secondary" pendingLabel="Activating client…">Confirm branches and activate</PendingButton></form>}</Card>{actor.role==="agency_owner"&&<Card className="stack">{specialist&&<form action={assignSpecialistAction}><input type="hidden" name="clientId" value={clientId}/><input type="hidden" name="userId" value={specialist.id}/><input type="hidden" name="assigned" value={String(assigned)}/><p>{specialist.full_name}: {assigned?"assigned":"not assigned"}</p><PendingButton variant="quiet" pendingLabel="Updating assignment…">{assigned?"Remove assignment":"Assign specialist"}</PendingButton></form>}<form action={updateClientStatusAction}><input type="hidden" name="clientId" value={clientId}/><input type="hidden" name="status" value="archived"/><PendingButton variant="danger" pendingLabel="Archiving client…">Archive client</PendingButton></form></Card>}</div></Section>
    <Section number="04" title="Add a location"><Card><form action={addLocationAction} className="form-grid"><input type="hidden" name="clientId" value={clientId}/><Label>Branch name<Input name="name" required/></Label><Label>Category<Input name="category"/></Label><Label>Address<Input name="address" required/></Label><Label>City<Input name="city" required/></Label><Label>Phone<Input name="phone"/></Label><Label>Page URL<Input name="websiteUrl"/></Label><div className="full"><PendingButton pendingLabel="Adding location…">Add location</PendingButton></div></form></Card></Section>
  </>;
}
