"use server";
import { revalidatePath } from "next/cache";
import { Resend } from "resend";
import { emailDeliveryKinds } from "@/domain/email-deliveries";
import { requireActor } from "@/lib/auth";
import { consumeQuota } from "@/lib/integrations/quota";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export async function createClientAction(form:FormData){const actor=await requireActor(["agency_owner"]);const db=await createSupabaseServerClient();const {error}=await db.from("clients").insert({agency_id:actor.agency_id,business_name:String(form.get("businessName")),industry:String(form.get("industry")),primary_contact_name:String(form.get("contactName"))||null,primary_contact_email:String(form.get("contactEmail"))||null,website:String(form.get("website"))||null,status:"draft"});if(error)throw error;revalidatePath("/agency/clients")}
export async function updateClientStatusAction(form:FormData){await requireActor(["agency_owner"]);const db=await createSupabaseServerClient();const clientId=String(form.get("clientId"));const status=String(form.get("status")) as "draft"|"under_agency_review"|"active"|"archived";const {error}=await db.from("clients").update({status}).eq("id",clientId);if(error)throw error;revalidatePath(`/agency/clients/${clientId}`);revalidatePath("/agency/clients")}
export async function addLocationAction(form:FormData){await requireActor(["agency_owner","seo_employee"]);const db=await createSupabaseServerClient();const clientId=String(form.get("clientId"));const {error}=await db.from("locations").insert({client_id:clientId,name:String(form.get("name")),address:String(form.get("address")),city:String(form.get("city")),phone:String(form.get("phone"))||null,website_url:String(form.get("websiteUrl"))||null,category:String(form.get("category"))||"Local business"});if(error)throw error;revalidatePath(`/agency/clients/${clientId}`)}
export async function assignSpecialistAction(form:FormData){await requireActor(["agency_owner"]);const db=await createSupabaseServerClient();const clientId=String(form.get("clientId"));const userId=String(form.get("userId"));const assigned=form.get("assigned")==="true";const result=assigned?await db.from("client_assignments").delete().eq("client_id",clientId).eq("user_id",userId):await db.from("client_assignments").insert({client_id:clientId,user_id:userId});if(result.error)throw result.error;revalidatePath(`/agency/clients/${clientId}`)}
export async function sendOnboardingInviteAction(form:FormData){const actor=await requireActor(["agency_owner"]);const db=await createSupabaseServerClient();const clientId=String(form.get("clientId"));const {data:client,error}=await db.from("clients").select("business_name,id").eq("id",clientId).single();if(error)throw error;await consumeQuota(actor,"email");const recipient=process.env.DEMO_CLIENT_RECIPIENT_EMAIL??"utkarsh.dubey.28.12.2005@gmail.com";let providerId:string|undefined;let failure:string|undefined;try{if(!process.env.RESEND_API_KEY||!process.env.RESEND_FROM_EMAIL)throw new Error("Resend credentials or verified sender are not configured.");const resend=new Resend(process.env.RESEND_API_KEY);const {data,error:sendError}=await resend.emails.send({from:process.env.RESEND_FROM_EMAIL,to:recipient,subject:`${client.business_name} · finish your Locally onboarding`,html:`<p>Your four-step onboarding is ready.</p><p><a href="${process.env.NEXT_PUBLIC_APP_URL}/login?next=/client/onboarding">Sign in and continue</a></p><small>This is a Locally demo delivered to the configured project inbox.</small>`});if(sendError)throw new Error(sendError.message);providerId=data?.id}catch(e){failure=e instanceof Error?e.message:"Unknown Resend error"}const {error:deliveryError}=await db.from("email_deliveries").insert({client_id:client.id,kind:emailDeliveryKinds.onboarding,recipient,status:failure?"failed":"sent",provider_message_id:providerId,error_message:failure,attempted_by:actor.id});if(deliveryError)throw deliveryError;revalidatePath(`/agency/clients/${clientId}`)}
export async function resetDemoAction(){await requireActor(["agency_owner"]);const db=await createSupabaseServerClient();const clientId="20000000-0000-4000-8000-000000000001";const now=Date.now();await db.from("clients").update({status:"submitted_by_client"}).eq("id",clientId).eq("is_demo",true);await db.from("onboarding_submissions").update({status:"draft",current_step:2,submitted_at:null,reviewed_at:null,answers_json:{business:{name:"Madhur Sweets",industry:"Sweet shop & gifting",contact:"Meera Arora"},locationsConfirmed:false}}).eq("client_id",clientId);const reviewDates=[5,48,96,144,192,240];for(let i=0;i<reviewDates.length;i++)await db.from("reviews").update({review_date:new Date(now-reviewDates[i]*3600000).toISOString(),status:i===3?"awaiting_approval":i===4?"draft":i===5?"mock_published":"needs_reply"}).eq("id",`60000000-0000-4000-8000-00000000000${i+1}`);await db.from("actions").update({status:"open",completed_at:null}).eq("client_id",clientId).eq("is_demo",true);await db.from("monthly_updates").update({status:"draft",approved_at:null,approved_by:null,sent_at:null}).eq("id","a0000000-0000-4000-8000-000000000001");revalidatePath("/agency");revalidatePath("/agency/clients");}
