"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { onboardingSteps } from "@/domain/onboarding";
import { requireActor } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Json } from "@/types/database";

export async function saveOnboardingStepAction(form:FormData){const actor=await requireActor(["client_owner"]);if(!actor.client_id)throw new Error("No client is attached to this account.");const step=Number(form.get("step")) as 1|2|3|4;const raw=Object.fromEntries([...form.entries()].filter(([key])=>!["step"].includes(key)).map(([k,v])=>[k,String(v)]));const parsed=onboardingSteps[step].safeParse(raw);if(!parsed.success)throw new Error(parsed.error.issues.map(i=>i.message).join(" · "));const db=await createSupabaseServerClient();const {data:existing}=await db.from("onboarding_submissions").select("answers_json").eq("client_id",actor.client_id).maybeSingle();const answers=typeof existing?.answers_json==="object"&&existing.answers_json&&!Array.isArray(existing.answers_json)?existing.answers_json:{};const merged={...answers,[`step${step}`]:parsed.data} as Json;const {error}=await db.from("onboarding_submissions").upsert({client_id:actor.client_id,submitted_by:actor.id,status:"draft",current_step:Math.min(step+1,4),answers_json:merged},{onConflict:"client_id"});if(error)throw error;revalidatePath("/client/onboarding");redirect(`/client/onboarding?step=${step+1}`)}
export async function submitOnboardingAction(){const actor=await requireActor(["client_owner"]);if(!actor.client_id)throw new Error("No client is attached to this account.");const db=await createSupabaseServerClient();const now=new Date().toISOString();const {error}=await db.from("onboarding_submissions").update({status:"submitted_by_client",submitted_at:now,current_step:4}).eq("client_id",actor.client_id);if(error)throw error;await db.from("clients").update({status:"submitted_by_client"}).eq("id",actor.client_id);revalidatePath("/client");redirect("/client?onboarding=submitted")}
export async function activateClientAction(form:FormData){const actor=await requireActor(["agency_owner"]);const clientId=String(form.get("clientId"));const db=await createSupabaseServerClient();const now=new Date().toISOString();const {error}=await db.from("clients").update({status:"active"}).eq("id",clientId);if(error)throw error;await db.from("onboarding_submissions").update({status:"active",reviewed_by:actor.id,reviewed_at:now}).eq("client_id",clientId);revalidatePath(`/agency/clients/${clientId}`)}
