"use server";
import { revalidatePath } from "next/cache";
import { Resend } from "resend";
import { requireActor } from "@/lib/auth";
import { consumeQuota } from "@/lib/integrations/quota";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export async function saveReportSummaryAction(form:FormData){await requireActor(["agency_owner","seo_employee"]);const db=await createSupabaseServerClient();const id=String(form.get("reportId"));const summary=String(form.get("summary")).trim();const status=form.get("submit")==="yes"?"awaiting_owner_approval":"draft";const {error}=await db.from("monthly_updates").update({agency_summary:summary,status}).eq("id",id);if(error)throw error;revalidatePath(`/agency/reports/${id}`)}
export async function approveAndSendReportAction(form:FormData){const actor=await requireActor(["agency_owner"]);const db=await createSupabaseServerClient();const id=String(form.get("reportId"));const {data:report,error}=await db.from("monthly_updates").select("*,clients!inner(business_name,id)").eq("id",id).single();if(error)throw error;const approvedAt=report.approved_at??new Date().toISOString();if(report.status!=="approved"&&report.status!=="sent"){const {error:approveError}=await db.from("monthly_updates").update({status:"approved",approved_by:actor.id,approved_at:approvedAt}).eq("id",id);if(approveError)throw approveError}await consumeQuota(actor,"email");const recipient=process.env.DEMO_CLIENT_RECIPIENT_EMAIL??"utkarsh.dubey.28.12.2005@gmail.com";let providerId:string|undefined;let failure:string|undefined;try{if(!process.env.RESEND_API_KEY||!process.env.RESEND_FROM_EMAIL)throw new Error("Resend credentials or verified sender are not configured.");const resend=new Resend(process.env.RESEND_API_KEY);const {data,error:sendError}=await resend.emails.send({from:process.env.RESEND_FROM_EMAIL,to:recipient,subject:`${report.clients.business_name} · monthly local-search update`,html:`<main style="font-family:Arial,sans-serif;max-width:640px;margin:auto"><h1>${report.clients.business_name}</h1><p>${report.agency_summary??"Your monthly update is ready."}</p><p><a href="${process.env.NEXT_PUBLIC_APP_URL}/client/reports/${id}">Read the approved report</a></p><small>Madhur Sweets and its data are fictional demo content.</small></main>`});if(sendError)throw new Error(sendError.message);providerId=data?.id}catch(e){failure=e instanceof Error?e.message:"Unknown Resend error"}await db.from("email_deliveries").insert({client_id:report.clients.id,monthly_update_id:id,kind:"monthly_report",recipient,status:failure?"failed":"sent",provider_message_id:providerId,error_message:failure,attempted_by:actor.id});if(!failure)await db.from("monthly_updates").update({status:"sent",sent_at:new Date().toISOString()}).eq("id",id);revalidatePath(`/agency/reports/${id}`);revalidatePath("/agency/reports")}
export async function saveFeedbackAction(form:FormData){const actor=await requireActor(["client_owner"]);const db=await createSupabaseServerClient();const reportId=String(form.get("reportId"));const usefulness=String(form.get("usefulness"));const comment=String(form.get("comment"));const categories=String(form.get("categories")??"").split(",").map(x=>x.trim()).filter(Boolean);const {error}=await db.from("report_feedback").upsert({monthly_update_id:reportId,client_user_id:actor.id,usefulness,categories_json:categories,comment,submitted_at:new Date().toISOString()},{onConflict:"monthly_update_id,client_user_id"});if(error)throw error;revalidatePath(`/client/reports/${reportId}`)}
